# Generated by Django 5.1.1 on 2024-09-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='checkin',
        ),
        migrations.AddField(
            model_name='checkin',
            name='medical_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.medicalrecord'),
        ),
    ]
