# Generated by Django 5.1.1 on 2024-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_medicalrecord_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='clinic.medicine'),
        ),
    ]
