# Generated by Django 5.1.1 on 2024-10-12 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0004_alter_medicalrecord_medicine"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"permissions": [("can_register", "Can register new patient")]},
        ),
    ]
