name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    # Install dependencies
    - name: Install dependencies
      run: npm ci
    
    # Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    # Setup Django and Add Test Users
    - name: Setup Django and Add Test Users
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        
        # Create admin user
        echo "
        from django.contrib.auth.models import User
        from clinic.models import Profile
        
        # Create admin user
        admin_user = User.objects.create_superuser(username='admin', email='admin@example.com', password='password123')
        Profile.objects.create(user=admin_user, user_type=Profile.UserType.ADMIN)
        
        # Create clinic staff user
        staff_user = User.objects.create_user(username='clinic_staff', email='staff@example.com', password='bingo123#@!')
        Profile.objects.create(user=staff_user, user_type=Profile.UserType.CLINIC_STAFF)
        " | python manage.py shell
        
        nohup python manage.py runserver 0.0.0.0:8000 &

    # Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test
    
    # Upload test results
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
